version: '3'
services:
  postgres:
    image: "postgres:10.5"
    environment:
      POSTGRES_USER: workshop
      POSTGRES_PASSWORD: 123
  api:
    build: .
    ports:
    - "3130:3130"
    depends_on:
      - postgres